name: Main

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Generate Changelog
        run: echo "# Good things have arrived" > ${{ github.workflow }}-CHANGELOG.txt
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          discussion_category_name: "Announcements"
          body_path: ${{ github.workflow }}-CHANGELOG.txt
          files: |
            a.txt
            b.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
