name: Main

on: push

jobs:
  build:
    permissions:
      contents: write
    # simulate a job that uploads multiple artifacts for multiple os's
    strategy:
      matrix:
        include:
          - asset: a.txt
            os: ubuntu-latest
          - asset: b.txt
            os: ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Generate Changelog
        run: echo "# Good things have arrived" > ${{ github.workflow }}-CHANGELOG.txt
      - name: Release
        uses: softprops/action-gh-release@master
        if: startsWith(github.ref, 'refs/tags/')
        with:
          #discussion_category_name: "Announcements"
          body_path: ${{ github.workflow }}-CHANGELOG.txt
          files: |
            ${{ matrix.asset }}
        #env:
        #  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        #GITHUB_REPOSITORY: softprops/action-gh-release-cross-test
